[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/api/news/*"
  to = "https://newsapi.org/v2/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/hf/*"
  to = "https://api-inference.huggingface.co/models/:splat"
  status = 200
  force = true
