[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/news/*"
  to = "https://newsapi.org/v2/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/geo/*"
  to = "https://nominatim.openstreetmap.org/:splat"
  status = 200
  force = true
